server:
  port: 8081
  servlet:
    context-path: /gatekeeper

spring:
  profiles:
    active:
      - dev
  application:
    name: gatekeeper
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration