server:
  port: 8080
  servlet:
    context-path: /gatekeeper

spring:
  application:
    name: gatekeeper
  datasource:
    url: jdbc:mysql://localhost:3306/gatekeeperdb
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration